server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_books_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456_Exol
